### ISSUE TITLE
Observables async advices

### ISSUE THREAD

**Issue by mgechev** [mgechev/aspect.js#3]
Since [observables](https://github.com/Reactive-Extensions/RxJS) got quite popular, it might be necessary in some cases to use observable advices.

This issue intents discussion of them.

**Comment by mgechev** [comment]
We can achieve the same result using `after` advices using `meta.method.result`.

**Comment by SamVerschueren** [comment]
I'd suggest reopening this issue. This is not always possible because, for instance, IndexedDB is async. So if you use IndexedDB as cache store, you can't prevent the original method from being executed if the data is already present in the cache.

My suggestion would be to not name them [sync_advices](https://github.com/mgechev/aspect.js/blob/master/lib/src/advices/sync_advices.ts), but just `advices`. Add some extra code in the advices that checks the result of each call (`void`, `value`, `Promise`, `Observable`). Handle it correctly and execute the next step.

I'm not sure if this is actually 100% possible though. What if the invoked method is synchronous, but the advices are asynchronous. This would result in the entire call becoming asynchronous, although actually the developer shouldn't care about it.

I think it's worth a discussion :).

**Comment by mgechev** [comment]
I think this puts another layer of complexity. What I'm using here is:

```
@beforeMethod(...)
foo(meta: Metadata) {
   meta.method.result.map(bar => baz(bar))
     .do(performSideEffect);
}
```

**Comment by SamVerschueren** [comment]
Yes it definitely adds complexity here. But the use case of preventing the method to execute when data is stored in an async cache (WebSQL, IndexedDB) can't be covered at the moment.

One way to solve this would be to attach an `invoke()` method to `meta.method`.

```ts
@beforeMethod(...)
foo(meta: Metadata) {
    meta.method.proceed = false;

    meta.method.result = retrieveFromCache().then(result => {
        if (result) {
            return result;
        }

        return meta.method.invoke();
    })
}
```

But then again, the developer has to make sure that `meta.method.result` returns the same type of result (Promise, Observable, ...) which is indeed more complex. But adding the `invoke()` method makes it possible to at least allow these kind of use cases. It's up to the developer of the `aspect` that the result matches the type.

**Comment by mgechev** [comment]
Yes, adding `meta.method.invoke()` makes sense.
